import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable()
export class PoolService {

  constructor(private http: HttpClient) {
  }

  list() {
    // TODO
    // return this.http.get('/api/pool').toPromise().then((resp: any) => {
    //  console.log(resp)
    // });
    return {
      'count': 7,
      'next': null,
      'previous': null,
      'results': [{
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 4,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': '.rgw.root',
        'type': 'replicated',
        'last_change': 37,
        'full': false,
        'pg_num': 8,
        'pgp_num': 8,
        'crush_ruleset': 0,
        'num_bytes': 1113,
        'num_objects': 4,
        'max_avail': 22016647168,
        'kb_used': 2,
        'percent_used': 0.0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'rgw': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 2,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'cephfs_data',
        'type': 'replicated',
        'last_change': 34,
        'full': false,
        'pg_num': 128,
        'pgp_num': 128,
        'crush_ruleset': 0,
        'num_bytes': 0,
        'num_objects': 0,
        'max_avail': 22016647168,
        'kb_used': 0,
        'percent_used': 0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'cephfs': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 3,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'cephfs_metadata',
        'type': 'replicated',
        'last_change': 34,
        'full': false,
        'pg_num': 128,
        'pgp_num': 128,
        'crush_ruleset': 0,
        'num_bytes': 2988,
        'num_objects': 21,
        'max_avail': 22016647168,
        'kb_used': 3,
        'percent_used': 0.0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'cephfs': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 5,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'default.rgw.control',
        'type': 'replicated',
        'last_change': 40,
        'full': false,
        'pg_num': 8,
        'pgp_num': 8,
        'crush_ruleset': 0,
        'num_bytes': 0,
        'num_objects': 8,
        'max_avail': 22016647168,
        'kb_used': 0,
        'percent_used': 0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'rgw': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 7,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'default.rgw.log',
        'type': 'replicated',
        'last_change': 46,
        'full': false,
        'pg_num': 8,
        'pgp_num': 8,
        'crush_ruleset': 0,
        'num_bytes': 0,
        'num_objects': 207,
        'max_avail': 22016647168,
        'kb_used': 0,
        'percent_used': 0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'rgw': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 6,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'default.rgw.meta',
        'type': 'replicated',
        'last_change': 44,
        'full': false,
        'pg_num': 8,
        'pgp_num': 8,
        'crush_ruleset': 0,
        'num_bytes': 373,
        'num_objects': 3,
        'max_avail': 22016647168,
        'kb_used': 1,
        'percent_used': 0.0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'rgw': {}}
      }, {
        'erasure_code_profile': null,
        'quota_max_objects': 0,
        'quota_max_bytes': 0,
        'size': 3,
        'min_size': 2,
        'crash_replay_interval': 0,
        'cache_mode': 'none',
        'tier_of': null,
        'write_tier': null,
        'read_tier': null,
        'target_max_bytes': 0,
        'hit_set_period': 0,
        'hit_set_count': 0,
        'id': 1,
        'cluster': '5cb4c964-02fd-3ea2-b693-04a282c6c920',
        'name': 'iscsi-images',
        'type': 'replicated',
        'last_change': 27,
        'full': false,
        'pg_num': 128,
        'pgp_num': 128,
        'crush_ruleset': 0,
        'num_bytes': 35,
        'num_objects': 5,
        'max_avail': 22016647168,
        'kb_used': 1,
        'percent_used': 0.0,
        'stripe_width': 0,
        'hit_set_params': {'type': 'none'},
        'tiers': [],
        'flags': ['hashpspool'],
        'compression_mode': 'none',
        'compression_algorithm': 'none',
        'compression_required_ratio': 0.0,
        'compression_max_blob_size': 0,
        'compression_min_blob_size': 0,
        'pool_snaps': [],
        'application_metadata': {'rbd': {}}
      }]
    };
  }

}
